const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: [
    './public/**/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}',
    './app/components/**/*.{erb,html}'
  ],
  theme: {
    extend: {
      fontFamily: {
        nunito: ['Nunito', 'sans-serif'],
      },
      colors: {
        'white': '#ffffff',
        'white-gray': '#f2f7ff',
        'bg-gray': '#F8F9FD',
        'field-gray': '#515151',
        'text-black': '#272525',
        'text-gray': '#383838',
        'light-gray': '#D0D0D0',
        'accent-blue': '#13acd5',
        'light-blue': '#5584ce',
        'gradient-violet': '#384295',
        'approved-green': '#10a141',
        'pending-yellow': '#f29325',
        'rejected-red': '#e54f53',
      },
      screens: {
        'custom-md': '900px', // Benutzerdefinierter Breakpoint für Bildschirme ab 900px
      },
    },
  },
  variants: {},
  plugins: [],
  safelist: [
    'text-accent-blue'
  ],
  corePlugins: [
    'accentColor',
    'accessibility',
    'alignContent',
    'alignItems',
    'alignSelf',
    'animation',
    'appearance',
    'aspectRatio',
    'backdropBlur',
    'backdropBrightness',
    'backdropContrast',
    'backdropFilter',
    'backdropGrayscale',
    'backdropHueRotate',
    'backdropInvert',
    'backdropOpacity',
    'backdropSaturate',
    'backdropSepia',
    'backgroundAttachment',
    'backgroundBlendMode',
    'backgroundClip',
    'backgroundColor',
    'backgroundImage',
    'backgroundOpacity',
    'backgroundOrigin',
    'backgroundPosition',
    'backgroundRepeat',
    'backgroundSize',
    'blur',
    'borderCollapse',
    'borderColor',
    'borderOpacity',
    'borderRadius',
    'borderSpacing',
    'borderStyle',
    'borderWidth',
    'boxDecorationBreak',
    'boxShadow',
    'boxShadowColor',
    'boxSizing',
    'breakAfter',
    'breakBefore',
    'breakInside',
    'brightness',
    'captionSide',
    'caretColor',
    'clear',
    'columns',
    'contain',
    'container',
    'content',
    'contrast',
    'cursor',
    'display',
    'divideColor',
    'divideOpacity',
    'divideStyle',
    'divideWidth',
    'dropShadow',
    'fill',
    'filter',
    'flex',
    'flexBasis',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'float',
    'fontFamily',
    'fontSize',
    'fontSmoothing',
    'fontStyle',
    'fontVariantNumeric',
    'fontWeight',
    'forcedColorAdjust',
    'gap',
    'gradientColorStops',
    'grayscale',
    'gridAutoColumns',
    'gridAutoFlow',
    'gridAutoRows',
    'gridColumn',
    'gridColumnEnd',
    'gridColumnStart',
    'gridRow',
    'gridRowEnd',
    'gridRowStart',
    'gridTemplateColumns',
    'gridTemplateRows',
    'height',
    'hueRotate',
    'hyphens',
    'inset',
    'invert',
    'isolation',
    'justifyContent',
    'justifyItems',
    'justifySelf',
    'letterSpacing',
    'lineClamp',
    'lineHeight',
    'listStyleImage',
    'listStylePosition',
    'listStyleType',
    'margin',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'mixBlendMode',
    'objectFit',
    'objectPosition',
    'opacity',
    'order',
    'outlineColor',
    'outlineOffset',
    'outlineStyle',
    'outlineWidth',
    'overflow',
    'overscrollBehavior',
    'padding',
    'placeContent',
    'placeItems',
    'placeSelf',
    'placeholderColor',
    'placeholderOpacity',
    'pointerEvents',
    'position',
    'preflight',
    'resize',
    'ringColor',
    'ringOffsetColor',
    'ringOffsetWidth',
    'ringOpacity',
    'ringWidth',
    'rotate',
    'saturate',
    'scale',
    'scrollBehavior',
    'scrollMargin',
    'scrollPadding',
    'scrollSnapAlign',
    'scrollSnapStop',
    'scrollSnapType',
    'sepia',
    'size',
    'skew',
    'space',
    'stroke',
    'strokeWidth',
    'tableLayout',
    'textAlign',
    'textColor',
    'textDecoration',
    'textDecorationColor',
    'textDecorationStyle',
    'textDecorationThickness',
    'textIndent',
    'textOpacity',
    'textOverflow',
    'textTransform',
    'textUnderlineOffset',
    'textWrap',
    'touchAction',
    'transform',
    'transformOrigin',
    'transitionDelay',
    'transitionDuration',
    'transitionProperty',
    'transitionTimingFunction',
    'translate',
    'userSelect',
    'verticalAlign',
    'visibility',
    'whitespace',
    'width',
    'willChange',
    'wordBreak',
    'zIndex'
  ]
}
